# Generated by Django 3.1.5 on 2021-01-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atracao',
            name='horario_funcionamento',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atracao',
            name='idade_minima',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
